### PR TITLE
fix: use different SecurityContexts for serverSocket vs client sockets

### LINKED ISSUE #151: `gha42` docker image breaks `at_client_sdk` functional tests
I think the new atsigncompany/at_proxyserver image is breaking at_client_sdk functional tests: https://github.com/atsign-foundation/at_client_sdk/actions/runs/22065841394/job/63783867954?pr=1828

CI passes when I pin to gha41: https://github.com/atsign-foundation/at_client_sdk/pull/1830

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
- fixes #151 
- fix: use different SecurityContexts for (1) the bound server socket (2) creation of new client sockets to the atServers
- chore: lint

**- How I did it**

**- How to verify it**
- Tests pass
- Once merged and new docker image published, will run at_client_sdk e2e tests to verify

### CODE REVIEW

File: packages/at_secondary_proxy/lib/src/secondary_connection_bridge.dart [hunk 1]
```diff
@@ -39,7 +42,7 @@ class SecondaryConnectionBridge {
 
   final _buffer = ByteBuffer(terminatingChar: '\n', capacity: 511);
 
-  Future<void> _clientOnData(data) async {
+  Future<void> _clientOnData(Uint8List data) async {
```
Comment (gkc) [inline packages/at_secondary_proxy/lib/src/secondary_connection_bridge.dart:45]: lint

File: packages/at_secondary_proxy/lib/src/secondary_proxy_server.dart [hunk 2]
```diff
@@ -19,38 +19,49 @@ class SecondaryProxyServer {
...
+    serverContext.usePrivateKey(_privateKeyLocation);
+    serverContext.setTrustedCertificates(_trustedCertificateLocation);
 
-    SecureServerSocket.bind(InternetAddress.anyIPv4, bindPort, secCon)
+    SecureServerSocket.bind(InternetAddress.anyIPv4, bindPort, serverContext)
         .then((SecureServerSocket secureServerSocket) {
       logger.info('Secure Socket listening on port $bindPort');
       _secureServerSocket = secureServerSocket;
-      _listen(_secureServerSocket);
+      SecurityContext clientContext = SecurityContext(withTrustedRoots: true);
```
Comment (gkc) [inline packages/at_secondary_proxy/lib/src/secondary_proxy_server.dart:39]: create a new SecurityContext which will be used when creating socket connections to atServers

**Review by cpswan — APPROVED** [review]
